Update install

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -89,34 +89,38 @@ fi
 #=================================================
 # PIP INSTALLATION
 #=================================================
-ynh_script_progression --message="Install weblate using PIP..." --weight=5
+ynh_script_progression --message="Install weblate using PIP..." --weight=80
 
-pushd $install_dir
-	python3 -m venv $install_dir/venv
-	source $install_dir/venv/bin/activate
-        ynh_exec_warn_less pip install --upgrade pip setuptools wheel toml pyyaml xxhash
+virtualenv --python=python3 "${install_dir}/venv"
+chown -R $app: "$install_dir"
 
-	# Read the "Note" section in https://docs.weblate.org/en/weblate-5.3/admin/install/venv-debian.html#python-modules
-	ynh_exec_warn_less pip install install --force-reinstall --no-binary :all: cffi
+#run source in a 'sub shell'
+(
+	set +o nounset
+	source "${install_dir}/venv/bin/activate"
+	set -o nounset
+	cd "${install_dir}"
 
-	ynh_exec_warn_less pip install Weblate=="$(ynh_app_upstream_version)"
+	sudo --user=$app $install_dir/venv/bin/pip install --upgrade pip setuptools wheel pkgconfig  xxhash
 
-	ynh_exec_warn_less pip install psycopg2-binary ruamel.yaml aeidon phply
-
+	# Read the "Note" section in https://docs.weblate.org/en/weblate-4.11/admin/install/venv-debian.html#python-modules
+	sudo --user=$app $install_dir/venv/bin/pip install --force-reinstall --no-binary :all: cffi
+	# Still needed with latest version of weblate?
+	sudo --user=$app BORG_OPENSSL_PREFIX=/usr/lib/x86_64-linux-gnu/ $install_dir/venv/bin/pip install Weblate=="$(ynh_app_upstream_version)"
+	sudo --user=$app $install_dir/venv/bin/pip install psycopg2-binary ruamel.yaml aeidon phply
+	#pip install pytz python-bidi PyYaML Babel pyuca pylibravatar py3dns psycopg2-binary phply django-redis hiredis aeidon ruamel.yaml
+	
 	# specific to YunoHost package:
-	ynh_exec_warn_less pip install django_sendmail_backend
-
-popd
+	sudo --user=$app $install_dir/venv/bin/pip install django_sendmail_backend
+)
 
 #=================================================
 # ADD A CONFIGURATION
 #=================================================
 ynh_script_progression --message="Adding a configuration file..." --weight=1
 
-# Configure redis
 redis_db=$(ynh_redis_get_free_db)
-ynh_app_setting_set --app="$app" --key=redis_db --value="$redis_db"
-
+ynh_app_setting_set --app=$app --key=redis_db --value="$redis_db"
 path="${path%/}"
 settings="$install_dir/venv/lib/$weblate_pypath/site-packages/weblate/settings.py"
 
@@ -142,20 +146,26 @@ chown -R "$app:www-data" "$install_dir/data"
 #==========================================
 ynh_script_progression --message="Filling up the database..." --weight=10
 
-export DJANGO_SETTINGS_MODULE="weblate.settings"
+(
+	set +o nounset
+	source "${install_dir}/venv/bin/activate"
+	set -o nounset
+	export DJANGO_SETTINGS_MODULE="weblate.settings"
+	cd "${install_dir}"
 
-ynh_exec_warn_less $install_dir/venv/bin/weblate migrate --noinput
-
-ynh_exec_warn_less $install_dir/venv/bin/weblate collectstatic --noinput
-
-ynh_exec_warn_less $install_dir/venv/bin/weblate createadmin --no-color \
+	# the user needs to be weblate for postgresql
+	ynh_exec_warn_less sudo --user=$app $install_dir/venv/bin/weblate migrate --noinput
+	# generate static files
+	ynh_exec_warn_less sudo --user=$app $install_dir/venv/bin/weblate collectstatic --noinput
+	ynh_exec_warn_less sudo --user=$app $install_dir/venv/bin/weblate createadmin --no-color \
 		--password "$password" \
 		--username "$admin" \
 		--email "$admin_mail"
 
-# Check the configuration
-# This may fail in some cases with errors, etc., but the app works and the user can fix issues later.
-ynh_exec_warn_less $install_dir/venv/bin/weblate check --deploy || true
+	# Check the configuration
+	# This may fail in some cases with errors, etc., but the app works and the user can fix issues later.
+	ynh_exec_warn_less sudo --user=$app $install_dir/venv/bin/weblate check --deploy || true
+)
 
 #=================================================
 # SETUP SYSTEMD
@@ -181,7 +191,7 @@ ynh_use_logrotate --non-append
 ynh_script_progression --message="Integrating service in YunoHost..." --weight=3
 
 yunohost service add $app --log="/var/log/$app/weblate.log"
-yunohost service add "$app-celery" --log="/var/log/$app/weblate-celery.log"
+yunohost service add "$app-celery" --log="/var/log/$app/weblate-celery-w1.log"
 
 #=================================================
 # START SYSTEMD SERVICE
@@ -189,7 +199,7 @@ yunohost service add "$app-celery" --log="/var/log/$app/weblate-celery.log"
 ynh_script_progression --message="Starting a systemd service..." --weight=5
 
 ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/weblate.log" --line_match="spawned uWSGI"
-ynh_systemd_action --service_name="$app-celery" --action="start" --log_path="/var/log/$app/weblate-celery.log" --line_match="mingle: all alone"
+ynh_systemd_action --service_name="$app-celery" --action="start" --log_path="/var/log/$app/weblate-celery-celery.log" --line_match="mingle: all alone"
 
 #=================================================
 # END OF SCRIPT
