refactor to not use subshells anymore (I don’t even understand the purpose)

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -108,32 +108,23 @@ upgrade() {
 	#=================================================
 	ynh_script_progression "Install weblate using PIP..."
 
-	ynh_safe_rm "${install_dir}/venv"
-	virtualenv --python=python3 "${install_dir}/venv"
-	chown -R $app: "$install_dir"
-	#run source in a 'sub shell'
-	(
-		set +o nounset
-		source "${install_dir}/venv/bin/activate"
-		set -o nounset
-		cd "${install_dir}"
+# Remove old venv
+ynh_safe_rm "${install_dir}/venv"
 
-		sudo --user=$app $install_dir/venv/bin/pip install --upgrade pip setuptools wheel pkgconfig xxhash gunicorn
+pushd "$install_dir"
+    ynh_exec_as_app python3 -m venv "$install_dir/venv"
+    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade pip setuptools wheel pkgconfig xxhash gunicorn
+	
+	# Read the "Note" section in https://docs.weblate.org/en/weblate-4.11/admin/install/venv-debian.html#python-modules
+    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install --force-reinstall --no-binary :all: cffi
 
-	#temporary fix to prevent ERROR: Dependency 'girepository-2.0' is required but not found.
-	sudo --user=$app $install_dir/venv/bin/pip install --upgrade pip PyGObject==3.50.0
+	ynh_hide_warnings ynh_exec_as_app BORG_OPENSSL_PREFIX=/usr/lib/x86_64-linux-gnu/ "$install_dir/venv/bin/pip" install Weblate=="$(ynh_app_upstream_version)"
+	ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install psycopg2-binary ruamel.yaml aeidon phply boto3 google openai
 
-		# Read the "Note" section in https://docs.weblate.org/en/weblate-4.11/admin/install/venv-debian.html#python-modules
-		sudo --user=$app $install_dir/venv/bin/pip install --force-reinstall --no-binary :all: cffi
-		
-		# Still needed with latest version of weblate?
-		sudo --user=$app $install_dir/venv/bin/pip install --upgrade Weblate=="$new_version"
-		sudo --user=$app $install_dir/venv/bin/pip install psycopg2-binary ruamel.yaml aeidon phply boto3 google openai
-		#pip install pytz python-bidi PyYaML Babel pyuca pylibravatar py3dns psycopg2-binary phply django-redis hiredis aeidon ruamel.yaml
-		
-		# specific to YunoHost package:
-		sudo --user=$app $install_dir/venv/bin/pip install django_sendmail_backend
-	)
+	ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install django_sendmail_backend
+
+    ynh_safe_rm "$install_dir/.cache/pip"
+popd
 
 	#=================================================
 	# MODIFY A CONFIG FILE
@@ -158,36 +149,35 @@ upgrade() {
 	touch "$install_dir/local_settings.py"
 	ln -sf "$install_dir/local_settings.py" "$install_dir/venv/lib/$weblate_pypath/site-packages/weblate/local_settings.py"
 
-	#=================================================
-	# MIGRATE WEBLATE
-	#=================================================
-	ynh_script_progression "Run migration scripts..."
+#=================================================
+# MIGRATE WEBLATE
+#=================================================
+ynh_script_progression "Run migration scripts..."
 
-	ynh_systemctl --service="$app-celery" --action="start"
+ynh_systemctl --service="$app-celery" --action="start"
 
-	(
-		set +o nounset
-		source "${install_dir}/venv/bin/activate"
-		set -o nounset
-		export DJANGO_SETTINGS_MODULE="weblate.settings"
-		cd "${install_dir}"
+pushd $install_dir
+	# exec_as_app because it needs to be $app for postgresql
+	ynh_hide_warnings ynh_exec_as_app $install_dir/venv/bin/weblate migrate --noinput
 
-		sudo --user=$app $install_dir/venv/bin/weblate migrate --noinput
-		sudo --user=$app $install_dir/venv/bin/weblate collectstatic --noinput
-		sudo --user=$app $install_dir/venv/bin/weblate setuplang
-		sudo --user=$app $install_dir/venv/bin/weblate setupgroups
-		sudo --user=$app $install_dir/venv/bin/weblate compilemessages
-                sudo --user=$app $install_dir/venv/bin/weblate compress
+	ynh_hide_warnings ynh_exec_as_app $install_dir/venv/bin/weblate createadmin --no-color \
+		--password "$password" \
+		--username "$admin" \
+		--email "$admin_mail"
 
-		# Check the configuration
-		# This may fail in some cases with errors, etc., but the app works and the user can fix issues later.
-		if [ "$new_version" == "$(ynh_app_upstream_version)" ]; then
-		ynh_hide_warnings sudo --user=$app $install_dir/venv/bin/weblate check --deploy || true
-		fi
-	)
+	# generate static files
+	ynh_hide_warnings ynh_exec_as_app $install_dir/venv/bin/weblate collectstatic --noinput
 
-	ynh_systemctl --service="$app-celery" --action="stop"
-}
+	# https://docs.weblate.org/en/latest/admin/install/venv-debian.html
+	ynh_hide_warnings ynh_exec_as_app $install_dir/venv/bin/weblate compress
+
+	# Check the configuration
+	# This may fail in some cases with errors, etc., but the app works and the user can fix issues later.
+	ynh_hide_warnings ynh_exec_as_app $install_dir/venv/bin/weblate check --deploy || true
+
+popd
+
+ynh_systemctl --service="$app-celery" --action="stop"
 
 file_version="${install_dir}/venv/lib/$weblate_pypath/site-packages/weblate/__init__.py"
 if [ -e $file_version ]
