try to simplify things

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -110,33 +110,27 @@ ynh_add_systemd_config --service="$app-celery" --template="celery-weblate.servic
 upgrade() {
 	new_version=$1
 	settings_template=$2
-	#=================================================
-	# PIP INSTALLATION
-	#=================================================
-	ynh_script_progression --message="Install weblate using PIP..." --weight=15
+#=================================================
+# PIP INSTALLATION
+#=================================================
+ynh_script_progression --message="Install weblate using PIP..." --weight=5
 
-	ynh_secure_remove --file="${install_dir}/venv"
-	virtualenv --python=python3 "${install_dir}/venv"
-	chown -R $app: "$install_dir"
+pushd $install_dir
+	python3 -m venv $install_dir/venv
+	source $install_dir/venv/bin/activate
+    ynh_exec_warn_less pip install --upgrade pip setuptools wheel pkgconfig  xxhash
 
-	#run source in a 'sub shell'
-	(
-		set +o nounset
-		source "${install_dir}/venv/bin/activate"
-		set -o nounset
-		cd "${install_dir}"
+	# Read the "Note" section in https://docs.weblate.org/en/weblate-5.3/admin/install/venv-debian.html#python-modules
+	ynh_exec_warn_less pip install install --force-reinstall --no-binary :all: cffi
 
-		sudo --user=$app $install_dir/venv/bin/pip install --upgrade pip setuptools wheel pkgconfig xxhash
+	ynh_exec_warn_less pip install Weblate=="$(ynh_app_upstream_version)"
 
-		# Read the "Note" section in https://docs.weblate.org/en/weblate-4.11/admin/install/venv-debian.html#python-modules
-		sudo --user=$app $install_dir/venv/bin/pip install --force-reinstall --no-binary :all: cffi
-		# Still needed with latest version of weblate?
-		sudo --user=$app $install_dir/venv/bin/pip install --upgrade Weblate=="$new_version"
-		sudo --user=$app $install_dir/venv/bin/pip install psycopg2-binary ruamel.yaml aeidon phply
-		#pip install pytz python-bidi PyYaML Babel pyuca pylibravatar py3dns psycopg2-binary phply django-redis hiredis aeidon ruamel.yaml
-		# specific to YunoHost package:
-		sudo --user=$app $install_dir/venv/bin/pip install django_sendmail_backend
-	)
+	ynh_exec_warn_less pip install psycopg2-binary ruamel.yaml aeidon phply
+
+	# specific to YunoHost package:
+	ynh_exec_warn_less pip install django_sendmail_backend
+
+popd
 
 	#=================================================
 	# MODIFY A CONFIG FILE
@@ -165,25 +159,23 @@ upgrade() {
 
 	ynh_systemd_action --service_name="$app-celery" --action="start"
 
-	(
-		set +o nounset
-		source "${install_dir}/venv/bin/activate"
-		set -o nounset
-		export DJANGO_SETTINGS_MODULE="weblate.settings"
-		cd "${install_dir}"
+	export DJANGO_SETTINGS_MODULE="weblate.settings"
 
-		sudo --user=$app $install_dir/venv/bin/weblate migrate --noinput
-		sudo --user=$app $install_dir/venv/bin/weblate collectstatic --noinput
-		sudo --user=$app $install_dir/venv/bin/weblate setuplang
-		sudo --user=$app $install_dir/venv/bin/weblate setupgroups
-		sudo --user=$app $install_dir/venv/bin/weblate compilemessages
-		
-		# Check the configuration
-		# This may fail in some cases with errors, etc., but the app works and the user can fix issues later.
-		if [ "$new_version" == "$(ynh_app_upstream_version)" ]; then
-			sudo --user=$app $install_dir/venv/bin/weblate check --deploy || true
-		fi
-	)
+	ynh_exec_warn_less $install_dir/venv/bin/weblate migrate --noinput
+
+	ynh_exec_warn_less $install_dir/venv/bin/weblate collectstatic --noinput
+
+	ynh_exec_warn_less $install_dir/venv/bin/weblate setuplang
+
+	ynh_exec_warn_less $install_dir/venv/bin/weblate setupgroups
+
+	ynh_exec_warn_less $install_dir/venv/bin/weblate compilemessages
+
+	# Check the configuration
+	# This may fail in some cases with errors, etc., but the app works and the user can fix issues later.
+	if [ "$new_version" == "$(ynh_app_upstream_version)" ]; then
+		ynh_exec_warn_less $install_dir/venv/bin/weblate check --deploy || true
+	fi
 
 	ynh_systemd_action --service_name="$app-celery" --action="stop"
 }
@@ -230,7 +222,7 @@ ynh_use_logrotate --non-append
 ynh_script_progression --message="Integrating service in YunoHost..." --weight=2
 
 yunohost service add $app --log="/var/log/$app/weblate.log"
-yunohost service add "$app-celery" --log="/var/log/$app/weblate-celery-w1.log"
+yunohost service add "$app-celery" --log="/var/log/$app/weblate-celery.log"
 
 #=================================================
 # START SYSTEMD SERVICES
@@ -238,7 +230,7 @@ yunohost service add "$app-celery" --log="/var/log/$app/weblate-celery-w1.log"
 ynh_script_progression --message="Starting systemd services..." --weight=5
 
 ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/weblate.log" --line_match="spawned uWSGI"
-ynh_systemd_action --service_name="$app-celery" --action="start" --log_path="/var/log/$app/weblate-celery-celery.log" --line_match="mingle: all alone"
+ynh_systemd_action --service_name="$app-celery" --action="start" --log_path="/var/log/$app/weblate-celery.log" --line_match="mingle: all alone"
 
 #=================================================
 # END OF SCRIPT
